# Sponsorluk seçenekleri
# Projeyi desteklemek isteyenler için

# github: beyazitkolemen
# patreon: username
# open_collective: serverbond-agent
# ko_fi: username
# custom: ['https://paypal.me/username', 'https://www.buymeacoffee.com/username']

