services:
  serverbond-agent:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: serverbond-agent
    restart: unless-stopped
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - AGENT_TOKEN=${AGENT_TOKEN:-your-secure-token-here}
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    networks:
      - serverbond-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  serverbond-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
