name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r api/requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 api/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 api/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Format check with black
      run: |
        black --check api/
    
    - name: Type check with mypy
      run: |
        mypy api/ --ignore-missing-imports || true
    
    - name: Test with pytest
      run: |
        pytest tests/ -v || echo "Tests will be added later"
    
    - name: Check shell scripts
      run: |
        sudo apt-get install -y shellcheck
        shellcheck install.sh scripts/*.sh examples/*.sh || true

  lint-markdown:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Lint markdown files
      uses: avto-dev/markdown-lint@v1
      with:
        args: '*.md'
        ignore: 'node_modules'

